# Global axis directions
# x - right (red)
# z - up (blue)
# y - into the screen (green)

# Frame descriptions
# {b} chassis frame - centre of the mobile base in h,l,w
# {0} arm base
# {e} end effector - mid point between the open gripper
# {s} space/global reference

# Units
# Metres/radians

# Given parameters
# Trajectory
Tse_initial: [[0,0,1,0], [0,1,0,0], [-1,0,0,0.5], [0,0,0,1]]

Tsc_initial: [[1,0,0,1], [0,1,0,0], [0,0,1,0.025], [0,0,0,1]]
Tsc_final  : [[0,1,0,0], [-1,0,0,-1], [0,0,1,0.025], [0,0,0,1]]

# Bot
chassis:
  wheel_rad: 0.0475
  l: 0.235 # Between axle and {b}
  w: 0.15 # Between wheel centre and {b}
  gamma: [-0.785,0.785,-0.785,0.785] # wheels 1,3 = -pi/4, wheels 2,4 = pi/4
  height: 0.0963

arm:
  Tbo: [[1,0,0,0.1662],[0,1,0,0],[0,0,1,0.0026],[0,0,0,1]]   # The fixed offset from {0} to {b}
  Moe: [[1,0,0,0.033],[0,1,0,0],[0,0,1,0.6546],[0,0,0,1]]    # Home config {e} relative to {0}

  # Screw axes for the 5 joints expressed in {e} when the arm is at its home config.
  Blist: [[0,0,0,0,0],[0,-1,-1,-1,0],[1,0,0,0,1],[0,-0.5076,-0.3526,-0.2176,0],[0.033,0,0,0,0],[0,0,0,0,0]]

# User selected parameters
# Trajectory
Tce_standoff: [[-0.7071, 0 , 0.7071, 0],[0,1,0,0],[-0.7071, 0, -0.7071, 0.06],[0,0,0,1]]
Tce_grasp: [[-0.7071, 0 , 0.7071, 0.02],[0,1,0,0],[-0.7071, 0, -0.7071, -0.02],[0,0,0,1]]
timeScaling: 5      #3
trajType: "screw"   # cartesian

# Bot
initialConfig :
  chassis: [0.4,0,0.25]     # q = (phi, x, y)
  # chassis: [0,0,0]     # q = (phi, x, y)
  arm: [0,0,0,0,0]
  wheel: [0,0,0,0]
  gripper: 0

# limits
jointLimits: [[-2.9,2.9],[-1.1,1.5],[-2.5,2.5],[-1.7,1.7],[-2.89,2.89]]  # rad

velocityLimits:
  arm: [10,10,10,10,10]   # rad/s
  wheel: [3000,3000,3000,3000]    # rad/s

# Simulation
tanim: 0.01       # Animation snapshot timestep

# Controller
Kp: 1
Ki: 0     # 0.01
k: 1      # Number of configurations per tanim = 10ms 
